apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
    group: {{ .Values.backend.group }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.container.port }}
              name: http # added
          resources:
            limits:
              # memory: "2Gi"
              # cpu: 500m  # Assuming potential spikes, provide a buffer
            requests:
              memory: 256Mi
              cpu: 1000m  # Set above observed usage to avoid overly aggressive scaling
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.container.port }}
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.container.port }}
            initialDelaySeconds: 20
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.host }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: PORT
              value: {{ .Values.backend.container.port | quote }}
