apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-access-control
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.backend.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.frontend.name }}
    ports:
    - protocol: TCP
      port: {{ .Values.backend.container.port }}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-access-control
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.backend.name }}
    ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
