apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: backend-peer-auth
spec:
  selector:
    matchLabels:
      app: backend
  mtls:
    mode: STRICT
  portLevelMtls:
    4002:
      mode: DISABLE

---

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: postgres-peer-auth
spec:
  selector:
    matchLabels:
      app: postgres
  mtls:
    mode: STRICT
  portLevelMtls:
    5432:
      mode: DISABLE
  