apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    name: {{ .Values.frontend.name }}
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.image.containerPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
          # env:
          #   - name: NEXT_PUBLIC_BACKEND_HOST
          #     value: {{ .Values.backend.name }}
          #   - name: NEXT_PUBLIC_BACKEND_PORT
          #     value: {{ .Values.backend.container.port | quote }}